const stories = [
  {
    slug: "kitt",
    title: "Knight Rider's KITT",
    source: "Knight Rider, 1982",
    category: "AI",
    status: "Mostly Real",
    score: "8/10",
    image: "assets/kitt-ai-xray.jpeg",
    detailEyebrow: "Featured comparison",
    detailTitle: "KITT did not arrive as one magic car. Its pieces arrived everywhere.",
    detailIntro: "Knight Rider imagined one machine that could listen, reason, protect, and drive. Real life delivered the dream in layers: advanced driver assistance, connected vehicle systems, voice commands, cameras, radar, and AI software that keeps getting smarter.",
    summary: "An AI car that talks, drives, senses danger, and responds to its driver.",
    then: "KITT was imagined as a smart car with a voice, independent driving, threat detection, and a strong personality.",
    now: "Modern vehicles include driver assist, voice control, emergency braking, route intelligence, parking assist, cameras, radar, and connected software.",
    check: "Many pieces are real, but they are not yet combined into one fully human-like car that can safely operate everywhere."
  },
  {
    slug: "jurassic-park-deextinction",
    title: "Jurassic Park De-Extinction",
    source: "Jurassic Park, 1993",
    category: "DNA",
    status: "Partly Real",
    score: "6/10",
    image: "assets/dire-wolf-deextinction-blueprint.jpeg",
    detailEyebrow: "Genetic comeback",
    detailTitle: "De-extinction moved from blockbuster fantasy into real genetic experiments.",
    detailIntro: "Jurassic Park made revival science feel dramatic and instant. Real research is slower and much more careful, but gene editing and ancient DNA comparison have pushed the basic idea into real laboratories and public debate.",
    summary: "Ancient DNA and gene editing moved extinct-animal revival from fiction into real debate.",
    then: "The story imagined extinct animals brought back from ancient genetic material.",
    now: "Researchers have compared ancient dire wolf DNA with living canids and used gene editing to create gray wolves with selected dire-wolf-like traits.",
    check: "Dinosaurs are not back, and experts debate how close these animals are to true extinct species. Current work is better described as proxy animals with selected ancient traits."
  },
  {
    slug: "woolly-mammoth-revival",
    title: "Woolly Mammoth Revival",
    source: "Ice age imagination",
    category: "DNA",
    status: "In Progress",
    score: "7/10",
    image: "assets/deextinction-dna-blueprint.jpeg",
    detailEyebrow: "Cold return",
    detailTitle: "The woolly mammoth idea returned as trait engineering instead of perfect resurrection.",
    detailIntro: "Instead of cloning a pure original mammoth, researchers are working toward elephant embryos that carry mammoth-like cold-weather traits. That makes the science more practical, but also changes what “bringing back” really means.",
    summary: "Asian elephant DNA is being edited toward mammoth-like cold-weather traits.",
    then: "People imagined ancient extinct animals walking the earth again.",
    now: "Researchers are working on mammoth-like traits such as thick hair, cold adaptation, fat storage, smaller ears, and cold-resistant blood.",
    check: "The likely result would be a mammoth-like elephant, not a perfect original woolly mammoth."
  },
  {
    slug: "star-trek-communicator",
    title: "Star Trek Communicator",
    source: "Star Trek, 1966",
    category: "Communication",
    status: "Real Today",
    score: "10/10",
    image: "assets/communicator-mobile-blueprint.jpeg",
    detailEyebrow: "Communication jump",
    detailTitle: "The pocket communicator became the connected world.",
    detailIntro: "The fictional promise was a simple one: instant contact anywhere. Reality overshot the original vision by turning the communicator into a phone, camera, computer, wallet, map, and global network terminal all at once.",
    summary: "Small wireless communication became normal life.",
    then: "A handheld device gave crew members instant voice contact across distance.",
    now: "Smartphones, smartwatches, wireless earbuds, satellite messaging, and mobile video calls are everywhere.",
    check: "This is one of the clearest examples of sci-fi becoming daily reality."
  },
  {
    slug: "iron-man-jarvis",
    title: "Iron Man's Jarvis",
    source: "Iron Man, 2008",
    category: "AI",
    status: "Mostly Real",
    score: "8/10",
    image: "assets/ai-assistant-jarvis-blueprint.jpeg",
    detailEyebrow: "AI assistant jump",
    detailTitle: "The fictional AI butler became the everyday copilot.",
    detailIntro: "Jarvis represented a dream of calm, competent intelligence always ready to help. Today that idea lives across chat AI, voice assistants, smart homes, workplace copilots, and automation systems rather than one perfect assistant.",
    summary: "A personal AI assistant that understands, answers, and helps with complex tasks.",
    then: "Jarvis managed systems, responded naturally, and helped Tony Stark think and build.",
    now: "ChatGPT, Siri, Alexa, Google Assistant, Microsoft Copilot, smart homes, and AI work tools handle many assistant tasks.",
    check: "Today's AI is powerful, but it is not yet one perfect household, vehicle, and lab intelligence."
  },
  {
    slug: "back-to-the-future-video-calls",
    title: "Back to the Future Video Calls",
    source: "Back to the Future Part II, 1989",
    category: "Communication",
    status: "Real Today",
    score: "10/10",
    image: "assets/video-call-blueprint.jpeg",
    detailEyebrow: "Connection jump",
    detailTitle: "The future living-room call became the everyday meeting window.",
    detailIntro: "What looked futuristic on a giant home screen is now ordinary across work, family, and global communication. The exact hardware changed, but the underlying prediction landed almost perfectly.",
    summary: "Big-screen home video calls became ordinary.",
    then: "The film showed people speaking face to face through large home screens.",
    now: "Zoom, FaceTime, Teams, WhatsApp video, smart TVs, tablets, and conference rooms made this normal.",
    check: "The prediction landed almost completely, though the exact screens changed."
  },
  {
    slug: "minority-report-gesture-screens",
    title: "Minority Report Gesture Screens",
    source: "Minority Report, 2002",
    category: "Immersive",
    status: "Partly Real",
    score: "7/10",
    image: "assets/gesture-screen-blueprint.jpeg",
    detailEyebrow: "Interface jump",
    detailTitle: "The floating control wall became touch, motion, and spatial computing.",
    detailIntro: "The film version made gesture control look like the default future. Reality spread those ideas across many devices instead: touchscreens, VR tracking, AR overlays, motion sensors, and specialized control rooms.",
    summary: "Moving screens with hand gestures became touch, motion, VR, and AR control.",
    then: "Characters moved data across giant displays using hand movements in the air.",
    now: "Touchscreens, VR hand tracking, AR interfaces, motion sensors, and gesture controls exist today.",
    check: "Gesture control works in certain settings, but it has not replaced normal screens and keyboards."
  },
  {
    slug: "jetsons-robot-helper",
    title: "The Jetsons Robot Helper",
    source: "The Jetsons, 1962",
    category: "Home",
    status: "Partly Real",
    score: "6/10",
    image: "assets/robot-helper-blueprint.jpeg",
    detailEyebrow: "Home robotics jump",
    detailTitle: "The cartoon helper robot became a collection of real household machines.",
    detailIntro: "Rosie suggested one cheerful robot doing everything at home. Real life broke that dream into many tools: cleaning bots, warehouse robots, delivery systems, smart speakers, and early humanoid helpers.",
    summary: "Home robots moved from cartoon comedy to daily household tools.",
    then: "Rosie the robot handled chores and household help.",
    now: "Robot vacuums, smart speakers, delivery robots, warehouse robots, and early humanoid robots handle pieces of the dream.",
    check: "Helpful robots exist, but a complete all-purpose home helper is still developing."
  },
  {
    slug: "spy-movie-biometrics",
    title: "Spy Movie Biometrics",
    source: "Classic spy fiction",
    category: "AI",
    status: "Real Today",
    score: "9/10",
    image: "assets/spy-biometrics-blueprint.jpeg",
    detailEyebrow: "Identity lock",
    detailTitle: "The spy-movie retina scan became a normal part of phones, airports, and secure buildings.",
    detailIntro: "Biometric access used to signal secret bases, elite labs, and dramatic security scenes. Now body-based identity checks are ordinary consumer and enterprise technology, even while privacy concerns grow alongside them.",
    summary: "Fingerprints, face scans, and eye scans became everyday security.",
    then: "Secret bases and spies used body-based identity checks.",
    now: "Phones, airports, offices, banks, and security systems use fingerprints, face unlock, and other biometric checks.",
    check: "The core idea is real, although privacy and misuse concerns are serious."
  },
  {
    slug: "star-wars-holograms",
    title: "Star Wars Holograms",
    source: "Star Wars, 1977",
    category: "Immersive",
    status: "Partly Real",
    score: "5/10",
    image: "assets/hologram-communication-blueprint.jpeg",
    detailEyebrow: "Projected presence",
    detailTitle: "The floating sci-fi message inspired today’s AR, VR, and early telepresence systems.",
    detailIntro: "True midair hologram calls are still rare, but the dream changed how people imagine remote presence. Today’s volumetric capture, mixed reality, stage projections, and telepresence tools are all pieces of that same cultural blueprint.",
    summary: "Projected 3D people inspired AR, VR, and telepresence experiments.",
    then: "Characters appeared as glowing 3D messages and remote presences.",
    now: "AR, VR, volumetric displays, hologram-style concerts, and 3D telepresence are real in limited forms.",
    check: "We have impressive versions, but the simple everyday floating hologram call is not common yet."
  }
];

function getStoryBySlug(slug) {
  return stories.find((story) => story.slug === slug) || null;
}

window.PAST_TO_FUTURE_STORIES = stories;
window.getPastToFutureStoryBySlug = getStoryBySlug;
